### ISSUE TITLE
Openssl@3 giving SSL Certifcate Error

### ISSUE THREAD

**Issue by nspire8** [iamchokerman/homebrew-ani-cli#2]
Hi, I'm on an M1 mac and after installing the formula I was unable to get `ani-cli` to work. The search was always returning empty results. After poking around a bit, I could see that my system was pointing to `openssl@1.1` and homebrew was using the `openssl@3` certs.

I was able to fix the issue by changing the formula to explicitly point to `openssl@1.1`.

```
brew uninstall ani-cli
brew uninstall openssl@3
rm -rf /opt/homebrew/etc/openssl@3
# had some existing dependencies to openssl@1.1
brew uninstall --ignore-dependencies openssl@1.1
brew install openssl@1.1
brew install --build-from-source ./ani-cli.rb
```

This issue might be specific to me due to how I've setup my system. Consider pinning `openssl` -> `openssl1.1`?

**Comment by justchokingaround** [comment]
no i think this issue is not just for you specifically, i've already thought of that during testing, but since i had nobody else to test, i wasn't sure. tysm, i fixed it now! now i know its openssl@1.1 and not openssl@3 <3
